### ISSUE TITLE
Add SQRT feature

### ISSUE THREAD

**Issue by peter279k** [brick/math#18]
As title, I think this `math` package should add this `sqrt` feature.

**Comment by BenMorel** [comment]
Pull request welcome, I you feel like implementing it!

You'll need to make it work with all calculators, including `NativeCalculator` (without GMP or BCMath).

**Comment by BenMorel** [comment]
Fixed in #19.

**Comment by BenMorel** [comment]
Released in [0.8.3](https://github.com/brick/math/releases/tag/0.8.3) 👍
