### ISSUE TITLE
Adding additional methods to match the Java API.

### ISSUE THREAD

**Issue by RobertZenz** [brick/math#21]
Would you be accepting a patch which adds "aliases" for the existing methods to make the API match [the Java BigDecimal API](https://docs.oracle.com/javase/8/docs/api/java/math/BigDecimal.html)? For example an `add(...)` method which just forwards to `plus(...)`.

The reasoning is that the math classes are already fairly closely modeled to the Java ones, and making the API more in line with the Java one would make them easier to use for everyone coming from Java.

**Comment by BenMorel** [comment]
Hi, no sorry, I don't think it is a good design to have 2 ways to do a single thing, and I insist on using `plus()/minus()/...` vs `add()/subtract()/...` to emphasize the fact that these classes are immutable.

Sure, this project was largely inspired by Java, but it also differs in many aspects, and I don't think it's *that* hard to get use to other method names when switching to another language!
