### ISSUE TITLE
Why to have "Big" in all class names?

### ISSUE THREAD

**Issue by jkuchar** [brick/math#23]
Hi again! 🙂

I'm getting curious what was the reason why are all Brick\Math classes called "Big"Something. Yep, they are primarily used for big numbers. I have opened code which is using Brick\Math just to provide concepts or `integer`, `decimal` and `rational` (no big numbers).

There is no straightforward representation of rational or decimal numbers in plain PHP. For example `1/3` or `.3`. I care a lot about types and semantics. `int` or `float` number sub-sets does not match any of meaningful number subsets like `integers`, `decimal numbers` and `rational numbers`.

Brick\Math represents concept of decimal, rational and integers exactly. I would consider it good-enough reason to name these classes as `Decimal`, `Rational` and `Integer`. 

What is your point of view? I would be especially happy to hear arguments against this proposed change. Thanks!

**Comment by BenMorel** [comment]
Hi! 👋

IIRC correctly my first decimal implementation *was* called `Decimal`, but I later decided to match Java's `BigInteger` and `BigDecimal` classes.

It looks like these names are industry standard these days: [Java](https://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html), [Ruby](https://ruby-doc.org/stdlib-2.6.3/libdoc/bigdecimal/rdoc/BigDecimal.html), maybe others.

Also, I think I had fears that `integer` might become a reserved word at some point, in the light of early scalar type hinting discussions; this could have become a problem, just like you cannot create a `String` class anymore in PHP 7. It looks like this threat is over now though.

I'm not strongly against your suggestion, but I feel like `Big` makes easier the distinction between a class that would rely on native type capabilities (like, a 64 bits Integer), and a class specifically designed to deal with arbitrary-size numbers.

Usually, when you encounter a `Big-Something`, you *know* that you're dealing with an arbitrary-size number; when you encounter `Decimal` or `Integer`, you're unsure.

Oh, and it gives more visibility to the library [for people coming from a Java background](https://stackoverflow.com/q/4427020/759866) :)
(try Googling [BigInteger php](https://www.google.com/search?q=biginteger+php))

By the way, there may be some usefulness in creating lighter weight classes based on native types. I'm thinking specifically of this [Decimal class](https://github.com/brick/validation/blob/0.2.1/src/Internal/Decimal.php) that I created in another library to support [validation of numbers in forms](https://github.com/brick/validation/blob/0.2.1/src/Validator/NumberValidator.php), without adding a dependency on brick/math's `BigDecimal` (numbers in forms rarely, if ever, exceed 20 digits, and I noticed that some browsers use floating-point numbers to validate them anyway, so this limitation in precision is quite acceptable).

Right now this Decimal class is internal to the library in question, but could very well be extracted in another library if that's useful. This may be a point against your suggestion, if they're ever going to coexist in some project.

Happy to hear your thoughts!

**Comment by BenMorel** [comment]
I'm going to close this issue due to lack of feedback.
Please feel free to resume the discussion if needed!
