### ISSUE TITLE
The right way to get result value in string format is only using the  __toString() ? 

### ISSUE THREAD

**Issue by jgnovais** [brick/math#25]

**Comment by BenMorel** [comment]
If I understand your question correctly, yes.

This is a [magic method](https://www.php.net/manual/en/language.oop5.magic.php#object.tostring) though, to be used for casting to string:

```php
$a = BigDecimal::of('12.34');
$string = (string) $a; // equivalent to $a->__toString();
```

If I did not understand your question, please reformulate it.

**Comment by jgnovais** [comment]
Yes this is it. Thanks so much.
