### ISSUE TITLE
Adding arbitrary Length Numbers to MathPHP

### ISSUE THREAD

**Issue by Beakerboy** [brick/math#26]
I'm one of the developers of MathPHP, and I'm in the process of adding Arbitrary Length numbers to that library. It looks like you're interested in math, so If you would like to help out, please stop by and take a look (https://github.com/markrogoyski/math-php/). I've just finalized an arbitrary length Integer object, and plan of working on floating point numbers soon. One difference I see is my library supports and number base up to 256 since everything is stored as binary strings. It can also support any "alphabet" that the user specifies for their number base.

I've just stumbled on this package and thought I'd reach out.

**Comment by BenMorel** [comment]
Hi!

Thanks for reaching out. First of all congrats for your library, I've never stumbled upon it before, it really handles advanced (for me, at least!) mathematical concepts.

Indeed if you add arbitrary size integer/decimal support, our libraries will overlap somehow on this point, which is not really a problem but may lead to duplicate efforts. `brick/math`'s objective is to only provide the arbitrary size objects (integer/decimal/rational), and nothing more (but do it well).

This is particularly useful for anything related to [money](https://github.com/brick/money).

One of the strengths of brick/math is its ability to use GMP or BCMath functions when available, and to fall back to plain PHP when not (with a performance penalty). It may lack more advanced features, but so far there haven't been requests for these features despite > 1M downloads.

I'm afraid I won't have time to invest into translating what I've done here for another project, however if you want to avoid reinventing the wheel, and think that you can build your arbitrary-sized objects on top of `brick/math`, then by all means I'll be happy to help, including if this requires changes here (I'm still in `0.x` so quite flexible).

**Comment by Beakerboy** [comment]
I'm not the lead developer, I just submit a lot of code. One of the main points is to be free of dependencies, so no references to GMP, or BCMath in this project. These large numbers can then be used for things like cryptographic functions or matrix algebra. Just thought I'd let you know about the project in case you need some more mathematical objects, or want a place to put some code you've developed.

**Comment by Beakerboy** [comment]
I fully agree with you, but I’m not the lead dev. I’ve been using GMP to guide the design of my object so that down the road an interface can be used internally instead of the object.

**Comment by BenMorel** [comment]
That sounds like a wise approach.

In `brick/math`, this is achieved through the [Calculator](https://github.com/brick/math/blob/0.8.8/src/Internal/Calculator.php) abstract class. It's not an interface, as it contains helper methods, some of which can be overridden by child classes if they natively implement the function (e.g., `gcd()`).

Implementations:

- [BCMathCalculator](https://github.com/brick/math/blob/0.8.8/src/Internal/Calculator/BcMathCalculator.php)
- [GmpCalculator](https://github.com/brick/math/blob/0.8.8/src/Internal/Calculator/GmpCalculator.php)
- [NativeCalculator](https://github.com/brick/math/blob/0.8.8/src/Internal/Calculator/NativeCalculator.php) (plain PHP)
