### ISSUE TITLE
PHP 5.4 Support

### ISSUE THREAD

**Issue by nicholas-eden** [brick/math#3]
I've forked the repo and replaced all unsupported syntax with 5.4 supported implementations.

Would you mind creating a branch to be maintained separately?

**Comment by BenMorel** [comment]
PHP 5.4 is [way past its EOL](http://php.net/supported-versions.php), so I'm not considering to maintain a branch for it.

You're welcome to fork the project and maintain your own Composer package, though!

**Comment by nicholas-eden** [comment]
Alright, thanks for the reply.

We are stuck with it for the time being.
