### ISSUE TITLE
bcpow doesn't work with negative numbers

### ISSUE THREAD

**Issue by danilo-znamerovszkij** [brick/math#38]
BigDecimal::of(1)->power(-7) gives an error that the exponent should be of type integer, which doesn't let the use of negative numbers

**Comment by BenMorel** [comment]
The issue with negative exponents, is that they may return numbers with infinite decimal digits, so you'd have to change the `power()` signature to accept a scale and a rounding mode.

What I suggest, instead of:

```php
BigDecimal::of($x)->power(-$n);
```

You can do:

```php
BigDecimal::one()->dividedBy(BigDecimal::of($x)->power($n) /*, $scale, $roundingMode */);
```

And handle the scale/rounding as appropriate!

**Comment by danilo-znamerovszkij** [comment]
Thanks for quick reaction, that works well
