### ISSUE TITLE
Performance checks

### ISSUE THREAD

**Issue by vladyslavstartsev** [brick/math#39]
I would like to use this lib, but I'm concerned about performance of it.

I would be nice to see section like https://github.com/thecodingmachine/safe#performance-impact (and also this https://github.com/thecodingmachine/safe/tree/master/performance) to see performance results.

**Comment by BenMorel** [comment]
Hi, the performance is great when using GMP or BCMath. Of course when no extension is present, it has to perform calculations in pure PHP, which is much slower.

You're welcome to write a performance test suite and PR it!

**Comment by BenMorel** [comment]
Closing due to lack of feedback. Feel free to open a PR for a performance test suite!
