### ISSUE TITLE
1.0.0 release?

### ISSUE THREAD

**Issue by sekjun9878** [brick/math#4]
Hello,

Do you know when a 1.0.0 of this library will be released?

Thanks!

**Comment by BenMorel** [comment]
Hi, I'm not planning on releasing 1.0 for now, as new requirements / new ideas can show up at any time, and changing the API after 1.0 is released will be a pain for everyone.

That being said, you don't need 1.0 to use the library. The current versions are well tested, and production quality. If you lock your composer.json to a 0.x series, you won't have any trouble.

And this leaves me flexibility to introduce a few breaking changes by introducing a new 0.y series, as explained in the README.
