### ISSUE TITLE
Number Calculation interface

### ISSUE THREAD

**Issue by miloshavlicek** [brick/math#42]
Hi, it would be useful to have a Number Calculation interface that will contain methods like plus($that), minus($that), multipliedBy($that) etc...

At this time, BigNumber does not contain these methods and it's ok, however, an interface would be fine.

We can use simple generics notation for that:
https://phpstan.org/blog/generics-in-php-using-phpdocs
https://psalm.dev/docs/annotating_code/templated_annotations/

**Comment by BenMorel** [comment]
Hi, what’s the use case for this?

It’s not possible to do this for every method anyway, in particular dividedBy() has different signatures for every class!

**Comment by BenMorel** [comment]
Closing due to lack of feedback. Please comment if you wish to reopen!

**Comment by aldenw** [comment]
Here is an example of what I think the use case for this would be.  This is what I'm currently doing with a method to add any of the 3 current Big types.  Doing the same with subtract, etc.

```php
    /**
     * @param BigInteger|BigRational|BigDecimal $leftOperand
     * @param BigInteger|BigRational|BigDecimal $rightOperand
     *
     * @noinspection PhpDocSignatureInspection
     */
    public static function add(BigNumber $leftOperand, BigNumber $rightOperand): BigNumber
    {
        return $leftOperand->plus($rightOperand);
    }
```
An interface would make this safe from potential future Big types that may not implement `plus`, or implement it with a different signature.  Also provide better ide support.  Currently we have to force the ide to ignore.  

> It’s not possible to do this for every method anyway, in particular dividedBy()

Definitely true, but I think that doesn't reduce the value of an interface for those methods for which it is possible.
