### ISSUE TITLE
GitHub CI instead of Travis

### ISSUE THREAD

**Issue by alexeyshockov** [brick/math#45]
@BenMorel, what do you think about possibility of this move?

GitHub CI integrates nice into the process, you can see checks success/failure more granularly, and also it's a possibility to report errors back directly to a PR, as a comments (like CS errors, Psalm errors, etc.).

The only issue I'm seeing currently is that the build takes a lot of time, and [GitHub has limited time a project](https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions). It's 2000 minutes/month currently, so if a build takes about 10 minutes... We have kinda 200 build per month, that should be enough, considering commits/PR rate to this repo.

Another option is to switch partially, like move all the quick checks (code style, Psalm, etc.) to GitHub CI, and leave heavy unit tests in Travis. But I think it's better to keep this as the last option.

**Comment by BenMorel** [comment]
I've changed my mind, given that:

- Travis has started removing processing power for open-source projects and builds now take a lot of time to start;
- GitHub Actions do not seem to impose a limit for open-source projects: the 2,000 minutes / month limit seems to only apply to private repos!

This has been taken care of in 8fded77a8015236202cecd492d938f50d45a58e0.

The only thing I've not been able to integrate with GitHub Actions is the smoke check. Do you know if this is possible, @alexeyshockov?

**Comment by BenMorel** [comment]
It is possible, using another job and adding `needs:` to the main job: c2ed5a6551acd0caad7c328ef2ba86935ec17aff.

I've decided to revert to not using smoke tests, though, as I discovered that by default, GitHub Actions uses a fail-fast strategy, where pending jobs are cancelled if any job fails. This is good enough for us.


Move to GitHub Actions: done ✔️ !
