### ISSUE TITLE
brick/math method for gmp_random_range

### ISSUE THREAD

**Issue by Spomky** [brick/math#46]
Hi,

Thank you for this library. It solves most of my troubles with GMP and BCMath.
However in one of my projects, I use the method `gmp_random_range` but haven’t found any replacement here.
Is there an alternative to this method?

Many thanks.
Regards

**Comment by BenMorel** [comment]
Hi, there is no equivalent in brick/math for now, but I can definitely see a value in this. I may work on it at some point.

I'll keep this PR open as a feature request! 👍

**Comment by BenMorel** [comment]
Implemented as [BigInteger::randomRange()](https://github.com/brick/math/blob/cc07e7aa554d8c39b6692de0c5293f0064c118fc/src/BigInteger.php#L216-L255).

You can test it in the `master` branch!

**Comment by BenMorel** [comment]
Implemented [BigInteger::randomBits()](https://github.com/brick/math/blob/master/src/BigInteger.php#L216-L246) as well.

**Comment by BenMorel** [comment]
Released as [0.8.16](https://github.com/brick/math/releases/tag/0.8.16)! ✨
