### ISSUE TITLE
Feature Request: Implement lisachenko/z-engine

### ISSUE THREAD

**Issue by RikudouSage** [brick/math#61]
[lisachenko/z-engine](https://github.com/lisachenko/z-engine) is a great library that allows you to for example have objects comparable or use mathematical operations on them.

Example what would be possible:

```php
<?php
var_dump(new BigInteger(5) > new BigInteger(1)); // true
var_dump(new BigInteger(10) + new BigInteger(3)); // BigInteger with value 13
```

It could be implemented as an optional dependency instead of a hardwired one.

**Comment by BenMorel** [comment]
Hi, this project looks really interesting, thanks for the pointer!

As it stands though, it's definitely not mature/stable/mainstream enough to be considered for this library!
