### ISSUE TITLE
BigComplex

### ISSUE THREAD

**Issue by zjbarg** [brick/math#62]
Hi, 

Are you open to adding BigComplex to the package? Any current plans or previous decisions regarding this?

**Comment by BenMorel** [comment]
Hi, yes I'd accept a PR for this! What's your use case for `BigComplex`?

**Comment by zjbarg** [comment]
I'm working on something, hope to create a good looking PR in the near future.

The use case is an app for calculating communication circuits impedance. It is used by communication engineers.
