### ISSUE TITLE
exactlyDividedBy throwing a RoundingNecessaryException.

### ISSUE THREAD

**Issue by ivands** [brick/math#7]
The 'exactlyDividedBy' method is throwing a RoundingNecessaryException.
I'm guessing this shouldn't happen or am i missing something?

Example:
`BigDecimal::of(1)->exactlyDividedBy('1927.27900');`

PS, love your work and im using it in every PHP project i create.

**Comment by ivands** [comment]
Nvm it's probably because the output is an infinite repeating decimal.

**Comment by BenMorel** [comment]
Glad you solved your own problem :)
Indeed, an infinite repeating decimal causes a `RoundingNecessaryException`.

Thanks for the encouragement!
