### ISSUE TITLE
`gmp_export` equivalent

### ISSUE THREAD

**Issue by Spomky** [brick/math#70]
Hi,

I am not sure if there is an equivalent method for `gmp_export`.
In my case, I have a GMP object that I need to export using the following parameters:

```php
$bin = gmp_export($value, 1, GMP_MSW_FIRST | GMP_BIG_ENDIAN);
```

Any idea?

**Comment by BenMorel** [comment]
Hi, the only binary export option available right now is `BigInteger::toBytes()`, which outputs the number as Big Endian, which *may* be what you're looking for?

There is currently no support for little endian, and I have no idea what `GMP_MSW_FIRST` and `GMP_LSW_FIRST` do. Does that stand for Most/Least Signifiant Word? How many bytes is a word? When is it useful?

**Comment by BenMorel** [comment]
Glad this is useful to you! Adding an option to control endianness would be nice, though.

**Comment by Spomky** [comment]
Yes indeed.
I will propose a PR.

I also tried to find other useful GMP functions such as [`gmp_setbit`](https://www.php.net/manual/en/function.gmp-setbit) or [gmp_scan1](https://www.php.net/manual/en/function.gmp-scan1.php)/[gmp_scan0](https://www.php.net/manual/en/function.gmp-scan0.php).
I am not sure if such function exist on BCMath side, but it could be nice to add them as wall.

WDYT?

**Comment by BenMorel** [comment]
I'm not against a PR for those, what would you use `scan0`/`scan1` for, though?
