### ISSUE TITLE
Provide value of None-Number in NumberFormatException

### ISSUE THREAD

**Issue by Idrinth** [brick/math#8]
https://github.com/brick/math/blob/master/src/BigNumber.php#L67 throws an exception without providing the string that failed to be recognised as a number.
For ease of use and less catching and rethrowing of exceptions it would be helpful to adjust the message to contain the string, maybe along the lines of:
```php
throw new NumberFormatException("The given value '$value' does not represent a valid number.");
```

**Comment by BenMorel** [comment]
I reckon that this may be more convenient, but can't you read the value from the stack trace?

```
Brick\Math\Exception\NumberFormatException: The given value does not represent a valid number. in /mnt/hgfs/www/brick/math/src/BigNumber.php:67
Stack trace:
#0 /www/brick/math/src/BigDecimal.php(57): Brick\Math\BigNumber::of('xxx')
#1 ...
```

**Comment by Idrinth** [comment]
I'm not sure what the question has to do with the given issue. There is no doubt there are other ways of retrieving pretty much any desired information.

You do provide more information in https://github.com/brick/math/blob/master/src/Exception/ArithmeticException.php#L19 as well for example, most likely also to remove the need for a more expensive lookup of values. I'm not sure in what way these two cases differ to you.

**Comment by BenMorel** [comment]
I was talking about the exception cast to string, that contains the exception message as well as the function parameters at a glance. I usually have a look at the full exception log, hence the generic questioning about the usefulness of a single parameter value replicated in the exception message.

You're right about me already doing it in `ArithmeticException` though, so I'll stick with it.
