### ISSUE TITLE
BigDecimal and BigInteger should not be final classes.

### ISSUE THREAD

**Issue by yadakhov** [brick/math#9]
Great library.  I'm trying to extend the BigDecimal classes for my use case.  I'm doing some cryptography programming which uses hexadecimals.  So my version of BigDecimal should support base 16.

It's not possible to extend your class because the class is declared as final.

Perhaps you can remove the final keyword.

**Comment by BenMorel** [comment]
Hi, classes are final to avoid giving access to the protected constructor. The main reason being, if I have to change a protected function in a non-final class, this is considered a BC break, and following [semver](http://semver.org/), this would require releasing a new major version.

This is not (yet) a big deal as v1.0 is not released yet, but I'm interested to know more about your use case, maybe this is something we could add to the library?

**Comment by yadakhov** [comment]
I'm trying to use base 16 instead of base 10.

Similar to https://github.com/pear/Math_BigInteger/blob/trunk/Math/BigInteger.php#L259.  Note the second parameter is the base.

You are correct.  Changing the final keyword is a BC break.  I'll just fork and create my own version.

Thanks.

**Comment by BenMorel** [comment]
Did you notice that there is support already for base [2-36] in [parse()](https://github.com/brick/math/blob/c652d6d4a0a7dd6e4299fb31f0a197cf95034d49/src/BigInteger.php#L66) and [toBase()](https://github.com/brick/math/blob/c652d6d4a0a7dd6e4299fb31f0a197cf95034d49/src/BigInteger.php#L508)?

You can parse a string in base 16:

```php
$i = BigInteger::parse('123456ABCDEF', 16);
echo $i; // 20016001699311
```

But internally the BigInteger is always in base 10. What are you trying to achieve that you cannot do with the current BigInteger? Can you give me an example of the operations you want to run, and what result you expect?

**Comment by yadakhov** [comment]
BigInteger::parse('123456ABCDEF', 16); solves it for me.

Thanks.
